const genericDocuments = {
    pmegp: [
        "Identity proof",
        "PAN card",
        "Business/project details",
        "Bank account details",
        "Category certificate where applicable",
        "Any business registration or activity proof requested by the implementing authority",
    ],
    mudra: [
        "Identity proof",
        "PAN card",
        "Business proof or activity details",
        "Bank account details",
        "Address proof",
        "Any lender-specific documentation required for the chosen loan category",
    ],
    "stand-up-india": [
        "Identity proof",
        "PAN card",
        "Business plan or greenfield enterprise details",
        "Bank account details",
        "Category certificate for women/SC/ST applicants where applicable",
        "Any additional lender documentation required for the application",
    ],
};

export function getRoadmapConfig(scheme = {}) {
    const schemeId = String(scheme.id || "").toLowerCase();
    const documents = genericDocuments[schemeId] || [
        "Identity proof",
        "PAN card",
        "Business or activity related documents",
        "Address proof",
        "Any scheme-specific documents required by the implementing authority",
    ];

    const schemeSpecific = {
        pmegp: {
            steps: [
                {
                    id: "eligibility",
                    title: "Check Eligibility",
                    whatYouNeed: "Your profile information and the scheme match result for PMEGP.",
                    whoHandlesIt: "Yojana Setu provides guidance based on the current matching rules.",
                    expectedNext: "Prepare the required documents and application information.",
                    officialLabel: "View PMEGP Guidelines",
                },
                {
                    id: "documents",
                    title: "Prepare Documents",
                    whatYouNeed: documents,
                    whoHandlesIt: "Applicant",
                    expectedNext: "Submit the application through the official channel.",
                    officialLabel: "Official scheme information",
                },
                {
                    id: "submit",
                    title: "Submit Application",
                    whatYouNeed: "Completed application form and supporting documents.",
                    whoHandlesIt: "Applicant / implementing agency",
                    expectedNext: "Application review and follow-up by the relevant authority.",
                    officialLabel: "Launch application or official portal",
                },
                {
                    id: "review",
                    title: "Bank / Agency Review",
                    whatYouNeed: "Submitted application, business details, and support documents.",
                    whoHandlesIt: "Relevant bank / implementing agency",
                    expectedNext: "Decision, additional clarification, or requests for more information.",
                    officialLabel: "Check agency guidance",
                },
                {
                    id: "decision",
                    title: "Institutional Decision",
                    whatYouNeed: "The relevant authority or lender reviews the submitted application.",
                    whoHandlesIt: "Relevant authority / bank / implementing agency",
                    expectedNext: "Follow up through the official application channel if required.",
                    officialLabel: "Review official process",
                },
                {
                    id: "benefit",
                    title: "Benefit Processing Guidance",
                    whatYouNeed: "Any final formalities required by the relevant scheme or institution.",
                    whoHandlesIt: "Relevant implementing agency / bank",
                    expectedNext: "Benefit details depend on the official scheme process and institutional decision.",
                    officialLabel: "Official documentation",
                },
            ],
        },
        mudra: {
            steps: [
                {
                    id: "eligibility",
                    title: "Check Eligibility",
                    whatYouNeed: "Your profile information and current PMMY suitability based on loan requirement and business activity.",
                    whoHandlesIt: "Yojana Setu provides indicative eligibility guidance.",
                    expectedNext: "Prepare the required lender and business documents.",
                    officialLabel: "View MUDRA Details",
                },
                {
                    id: "documents",
                    title: "Prepare Documents",
                    whatYouNeed: documents,
                    whoHandlesIt: "Applicant / chosen lending institution",
                    expectedNext: "Apply through the relevant lender or official business channel.",
                    officialLabel: "Official MUDRA information",
                },
                {
                    id: "submit",
                    title: "Submit Application",
                    whatYouNeed: "Completed application and supporting documents for the selected loan category.",
                    whoHandlesIt: "Applicant / lender",
                    expectedNext: "Lender review and request for additional information if needed.",
                    officialLabel: "Visit lender or scheme portal",
                },
                {
                    id: "review",
                    title: "Bank / Agency Review",
                    whatYouNeed: "Submitted loan application and business details.",
                    whoHandlesIt: "Relevant lender / financial institution",
                    expectedNext: "Decision or follow-up on documentation and suitability.",
                    officialLabel: "Official lender guidance",
                },
                {
                    id: "decision",
                    title: "Institutional Decision",
                    whatYouNeed: "The chosen lender reviews the submitted loan application.",
                    whoHandlesIt: "Relevant lender / implementing authority",
                    expectedNext: "The lender may request clarification or provide next steps.",
                    officialLabel: "Official lender guidance",
                },
                {
                    id: "benefit",
                    title: "Repayment Setup Guidance",
                    whatYouNeed: "Repayment terms and final formalities provided by the lender, if applicable.",
                    whoHandlesIt: "Lender / bank",
                    expectedNext: "Review the lender's terms before accepting or using any facility.",
                    officialLabel: "Disbursement / lender details",
                },
            ],
        },
        "stand-up-india": {
            steps: [
                {
                    id: "eligibility",
                    title: "Check Eligibility",
                    whatYouNeed: "Your profile information, category details, business activity, and the requested loan amount.",
                    whoHandlesIt: "Yojana Setu provides indicative assistance based on the current matching rules.",
                    expectedNext: "Prepare the required lender and enterprise documents.",
                    officialLabel: "View Stand-Up India Details",
                },
                {
                    id: "documents",
                    title: "Prepare Documents",
                    whatYouNeed: documents,
                    whoHandlesIt: "Applicant / lender",
                    expectedNext: "Submit the application with the relevant bank or implementing agency.",
                    officialLabel: "Official Stand-Up India information",
                },
                {
                    id: "submit",
                    title: "Submit Application",
                    whatYouNeed: "Application form, business case, and supporting documents.",
                    whoHandlesIt: "Applicant / participating bank",
                    expectedNext: "Institutional review and evaluation.",
                    officialLabel: "Open official portal",
                },
                {
                    id: "review",
                    title: "Bank / Agency Review",
                    whatYouNeed: "Submitted business and category information, plus documentation support.",
                    whoHandlesIt: "Participating bank / implementing authority",
                    expectedNext: "Further clarification or assessment of eligibility and business viability.",
                    officialLabel: "Review bank guidance",
                },
                {
                    id: "decision",
                    title: "Institutional Decision",
                    whatYouNeed: "The participating bank or institution reviews the submitted information.",
                    whoHandlesIt: "Participating bank / scheme authority",
                    expectedNext: "The institution may request clarification or provide next steps.",
                    officialLabel: "Check official guidance",
                },
                {
                    id: "benefit",
                    title: "Benefit Processing Guidance",
                    whatYouNeed: "Any final compliance checks and formalities required by the official process.",
                    whoHandlesIt: "Bank / implementing agency",
                    expectedNext: "Benefit or financing details depend on the official process and institutional decision.",
                    officialLabel: "Lender or scheme guidance",
                },
            ],
        },
    };

    return schemeSpecific[schemeId] || {
        steps: [
            {
                id: "eligibility",
                title: "Check Eligibility",
                whatYouNeed: "Your profile information and scheme match details.",
                whoHandlesIt: "Yojana Setu provides indicative eligibility guidance.",
                expectedNext: "Prepare the required documents and confirm the application route.",
                officialLabel: "Official scheme information",
            },
            {
                id: "documents",
                title: "Prepare Documents",
                whatYouNeed: documents,
                whoHandlesIt: "Applicant",
                expectedNext: "Submit the application through the official channel.",
                officialLabel: "Refer to the official scheme guidelines.",
            },
            {
                id: "submit",
                title: "Submit Application",
                whatYouNeed: "Completed application and required supporting documents.",
                whoHandlesIt: "Applicant / implementing agency",
                expectedNext: "Application review.",
                officialLabel: "Official scheme information",
            },
            {
                id: "review",
                title: "Bank / Agency Review",
                whatYouNeed: "Submitted application and supporting documents.",
                whoHandlesIt: "Relevant bank / government agency",
                expectedNext: "Decision or further clarification.",
                officialLabel: "Official scheme information",
            },
            {
                id: "decision",
                title: "Institutional Decision",
                whatYouNeed: "The relevant authority or institution reviews the submitted application.",
                whoHandlesIt: "Relevant authority / bank / implementing agency",
                expectedNext: "Follow up through the official application channel if required.",
                officialLabel: "Official scheme information",
            },
            {
                id: "benefit",
                title: "Benefit Processing Guidance",
                whatYouNeed: "Completion of any final formalities required by the official process.",
                whoHandlesIt: "Relevant implementing agency / bank",
                expectedNext: "Benefit details depend on scheme rules and the institutional decision.",
                officialLabel: "Official scheme information",
            },
        ],
    };
}
